version: "3"
services: 
  db: 
    image: postgres:10.7
    environment: 
      POSTGRES_PASSWORD:  postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: v2
    volumes: 
      # - ./docker/pgdata:/var/lib/postgresql/data
      - /data/pgdata:/var/lib/postgresql/data
    ports: 
      - '5431:5432'

  serv:
    image: node-js-rest
    depends_on: 
      - db
    ports: 
      - "3001:3001"
    environment: 
      DB_HOST: db
